// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsqlsrdsljlvideihevy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcWxzcmRzbGpsdmlkZWloZXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDk5OTQsImV4cCI6MjA3MzM4NTk5NH0.guK4SoN6L5KINJg7FPVlnq9IqIbNdIOwilHqcdNv3EQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});