// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdjiimzpswmeqvixcmfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkamlpbXpwc3dtZXF2aXhjbWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxOTgwNzIsImV4cCI6MjA3OTc3NDA3Mn0.pa8r-VavPNaqEPqkGgKtHz50mlLJSRdz_JSaJh6TdWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});